### ISSUE TITLE
[help] Why oom-killer not kill the file-starve process?

### ISSUE THREAD

**Issue by chenk008** [hakavlad/file-starve#1]
Why oom-killer not kill the file-starve process? 

~~I found other processes were killed by the oom-killer, that is I change the oom_score_adj~~

**Comment by chenk008** [comment]
Because the file-starve always allocate a little memory?

**Comment by hakavlad** [comment]
It's strange. `file-starve` sets `/proc/self/oom_score_adj`=1000 before starting. Maybe oom-killer killed other process with oom_score_adj=1000? What is the process of Killer’s victim, what is interesting in the journal?

**Comment by hakavlad** [comment]
```
with open('/proc/self/oom_score_adj', 'w') as f:
    f.write('1000\n')
```
file-starve should be the first victim.

**Comment by hakavlad** [comment]
>Why oom-killer not kill the file-starve process?

OOOM Killer does not kill anyone at all?

**Comment by hakavlad** [comment]
try to execute `file-starve -t 1`, maybe it will be killed in this case.

**Comment by chenk008** [comment]
@hakavlad Sorry, I have changed  oom_score_adj to -1000 in one test.

**Comment by chenk008** [comment]
I changed oom_score_adj to 1000, the system always stuck without oom
